# Generated by Django 5.1.6 on 2025-04-09 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0003_suricatalog'),
    ]

    operations = [
        migrations.AddField(
            model_name='suricatalog',
            name='destination_port',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='suricatalog',
            name='source_port',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='suricatalog',
            name='timestamp',
            field=models.DateTimeField(),
        ),
    ]
