# Generated by Django 5.1.6 on 2025-06-12 17:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0005_airecommendation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=255)),
                ('ip_address', models.GenericIPAddressField()),
                ('os_info', models.TextField()),
                ('scan_type', models.CharField(max_length=50)),
                ('scanned_at', models.DateTimeField(auto_now_add=True)),
                ('scanned_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ConfigurationIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('security', 'Security'), ('performance', 'Performance'), ('network', 'Network'), ('system', 'System'), ('service', 'Service'), ('storage', 'Storage')], max_length=20)),
                ('severity', models.CharField(choices=[('info', 'Info'), ('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('config_file', models.CharField(blank=True, max_length=512, null=True)),
                ('config_line', models.TextField(blank=True, null=True)),
                ('current_value', models.TextField(blank=True, null=True)),
                ('recommended_value', models.TextField(blank=True, null=True)),
                ('fix_command', models.TextField(blank=True, null=True)),
                ('is_auto_fixable', models.BooleanField(default=False)),
                ('is_fixed', models.BooleanField(default=False)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('system_scan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chatbot.systemscan')),
            ],
        ),
    ]
