# Generated by Django 5.1.6 on 2025-06-15 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0006_systemscan_configurationissue'),
    ]

    operations = [
        migrations.AddField(
            model_name='configurationissue',
            name='ai_impact',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='configurationissue',
            name='ai_recommendation',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='configurationissue',
            name='ai_risk',
            field=models.TextField(blank=True, null=True),
        ),
    ]
