# Generated by Django 5.1.6 on 2026-01-11 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0011_aiintrusionlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiintrusionlog',
            name='destination_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
