# Generated by Django 5.1.6 on 2026-08-02 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0012_aiintrusionlog_destination_ip'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentIncident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem', models.TextField()),
                ('solution', models.TextField()),
                ('tools_used_json', models.TextField(default='[]')),
                ('category', models.CharField(default='general', max_length=100)),
                ('session_id', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Agent Incident',
                'verbose_name_plural': 'Agent Incidents',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkspaceInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workspace_path', models.CharField(max_length=512, unique=True)),
                ('framework', models.CharField(default='unknown', max_length=100)),
                ('language', models.CharField(default='unknown', max_length=100)),
                ('database', models.CharField(default='unknown', max_length=100)),
                ('web_server', models.CharField(default='unknown', max_length=100)),
                ('dependencies_json', models.TextField(default='[]')),
                ('deployment_json', models.TextField(default='[]')),
                ('has_docker', models.BooleanField(default=False)),
                ('has_nginx', models.BooleanField(default=False)),
                ('context_json', models.TextField(default='{}')),
                ('last_scanned', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Workspace Info',
                'verbose_name_plural': 'Workspace Info',
            },
        ),
    ]
