# Generated by Django 5.1.6 on 2026-08-02 10:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0013_agentincident_workspaceinfo_chatsession_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfrastructureNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('node_type', models.CharField(choices=[('server', 'Server'), ('service', 'Service'), ('application', 'Application'), ('container', 'Container'), ('database', 'Database')], max_length=50)),
                ('properties', models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='ServerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('hostname', models.CharField(max_length=255)),
                ('ip', models.GenericIPAddressField()),
                ('os', models.CharField(max_length=100)),
                ('ssh_credential_ref', models.CharField(blank=True, max_length=255)),
                ('last_health_check', models.DateTimeField(auto_now=True)),
                ('services', models.JSONField(blank=True, default=list)),
            ],
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant'), ('tool', 'Tool')], default='user', max_length=20),
        ),
        migrations.AddField(
            model_name='chatsession',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='chatbot.workspaceinfo'),
        ),
        migrations.CreateModel(
            name='AgentArtifact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.CharField(max_length=1024)),
                ('action_type', models.CharField(max_length=50)),
                ('old_content', models.TextField(blank=True, null=True)),
                ('new_content', models.TextField(blank=True, null=True)),
                ('diff', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artifacts', to='chatbot.workspaceinfo')),
            ],
        ),
        migrations.CreateModel(
            name='AgentEventLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='chatbot.chatsession')),
            ],
        ),
        migrations.CreateModel(
            name='InfrastructureEdge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation_type', models.CharField(max_length=100)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_edges', to='chatbot.infrastructurenode')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_edges', to='chatbot.infrastructurenode')),
            ],
        ),
        migrations.CreateModel(
            name='ToolExecutionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tool_name', models.CharField(max_length=100)),
                ('input_parameters', models.TextField(blank=True)),
                ('output_result', models.TextField(blank=True)),
                ('status', models.CharField(max_length=50)),
                ('execution_time', models.FloatField(default=0.0)),
                ('risk_level', models.CharField(default='LOW', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tool_logs', to='chatbot.chatsession')),
            ],
        ),
    ]
