# Generated by Django 5.1.6 on 2026-08-03 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0014_infrastructurenode_serverprofile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentartifact',
            name='session_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
