# Generated by Django 5.1.6 on 2026-08-03 09:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0015_agentartifact_session_id_chatsession_title'),
    ]

    operations = [

        migrations.CreateModel(
            name='Investigation',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('status', models.CharField(default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investigations', to='chatbot.chatsession')),
            ],
        ),
        migrations.CreateModel(
            name='InvestigationFinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('investigation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='findings', to='chatbot.investigation')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='InvestigationTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('task_order', models.IntegerField(default=0)),
                ('investigation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='chatbot.investigation')),
            ],
            options={
                'ordering': ['task_order'],
            },
        ),
    ]
