# Generated by Django 5.1.6 on 2026-08-09 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0016_chatsession_title_investigation_investigationfinding_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Display name for the model option', max_length=100)),
                ('model_id', models.CharField(help_text='Model identifier sent to engine (e.g. OPENCODE, GROQ, mistral-large-latest)', max_length=100)),
                ('provider', models.CharField(choices=[('9router', '9Router'), ('nvidia', 'NVIDIA AI'), ('ollama', 'Ollama Local'), ('mistral', 'Mistral AI'), ('openai', 'OpenAI'), ('other', 'Other')], default='9router', max_length=50)),
                ('base_url', models.CharField(blank=True, help_text='Optional custom Base URL (e.g. http://localhost:20128/v1)', max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]

