# Generated by Django 5.1.6 on 2026-08-09 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0017_aimodel_chatsession_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemArchitectureCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mermaid_diagram', models.TextField(blank=True, null=True)),
                ('services_json', models.TextField(blank=True, null=True)),
                ('insights_json', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='chatsession',
            name='title',
            field=models.CharField(default='New Chat', max_length=255),
        ),
    ]
