# Generated by Django 5.1.6 on 2026-08-12 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0018_systemarchitecturecache_chatsession_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='aimodel',
            name='api_key',
            field=models.CharField(blank=True, help_text='Optional API Key for custom provider', max_length=255, null=True),
        ),
    ]
