# Generated by Django 5.1.6 on 2026-10-04 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0030_backfill_investigation_context_refs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aimodel',
            name='provider',
            field=models.CharField(choices=[('9router', '9Router (OpenAI-compatible)'), ('openai', 'OpenAI'), ('anthropic', 'Anthropic (native API)'), ('nvidia', 'NVIDIA AI'), ('ollama', 'Ollama Local'), ('mistral', 'Mistral AI'), ('groq', 'Groq'), ('openrouter', 'OpenRouter (OpenAI-compatible)'), ('other', 'Other (OpenAI-compatible)')], default='9router', max_length=50),
        ),
    ]
