# Generated by Django 5.1.6 on 2026-10-04 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0031_alter_aimodel_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='aimodel',
            name='endpoint_type',
            field=models.CharField(choices=[('openai', 'OpenAI-compatible'), ('anthropic', 'Anthropic native')], default='openai', help_text='Wire protocol: OpenAI-compatible (default) or Anthropic native Messages API', max_length=20),
        ),
        migrations.AlterField(
            model_name='aimodel',
            name='provider',
            field=models.CharField(choices=[('9router', '9Router'), ('nvidia', 'NVIDIA AI'), ('ollama', 'Ollama Local'), ('mistral', 'Mistral AI'), ('groq', 'Groq'), ('openai', 'OpenAI'), ('other', 'Other')], default='9router', max_length=50),
        ),
    ]
