# Generated by Django 5.1.6 on 2026-10-04 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0032_aimodel_endpoint_type_alter_aimodel_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='suricata_alerts_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
