# Generated by Django 5.1.6 on 2026-10-04 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0033_suricata_alerts_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentartifact',
            name='case_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=50),
        ),
    ]
