# Generated by Django 5.1.6 on 2026-10-05 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0034_agentartifact_case_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='aimodel',
            name='tool_choice',
            field=models.CharField(choices=[('any', 'any (force a tool call; Anthropic or langchain-normalised OpenAI)'), ('required', 'required (OpenAI standard forced tool call)'), ('auto', 'auto (model decides; use for thinking/reasoning models that reject forced calls)')], default='any', help_text="How tools are offered in the ReAct loop. DeepSeek thinking mode rejects 'any'/'required' - use 'auto' there.", max_length=16),
        ),
    ]
