# Generated by Django 5.1.6 on 2026-10-05 08:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0035_aimodel_tool_choice'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionMemory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_label', models.CharField(blank=True, default='', max_length=255)),
                ('topic_entities', models.JSONField(blank=True, default=list)),
                ('topic_keywords', models.JSONField(blank=True, default=list)),
                ('topic_history', models.JSONField(blank=True, default=list)),
                ('digest', models.TextField(blank=True, default='')),
                ('digest_upto', models.IntegerField(default=0)),
                ('session_entities', models.JSONField(blank=True, default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='thread_memory', to='chatbot.chatsession')),
            ],
        ),
    ]
