"""
Django settings for ai_config project.

Generated by 'django-admin startproject' using Django 5.1.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
import os
from decouple import config
SECRET_KEY = config("DJANGO_SECRET_KEY", default="default-secret-key")
OPENAI_KEY = config("OPENAI_API_KEY", default="openai-key")
GEMINI_KEY = config("GEMINI_API_KEY", default="gemini-key")
MISTRAL_API_KEY = config("MISTRAL_API_KEY", default="mistral-key")
ROUTER_API_KEY = config("ROUTER_API_KEY", default="")
NVIDIA_API_KEY = config("NVIDIA_API_KEY", default="")
GROQ_API_KEY = config("GROQ_API_KEY", default="")
ANTHROPIC_API_KEY = config("ANTHROPIC_API_KEY", default="")

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ['*']

OLLAMA_URL = config("OLLAMA_URL")
OLLAMA_MODEL = config("OLLAMA_MODEL")
OLLAMA_API_KEY = config("OLLAMA_API_KEY")

# Application definition

INSTALLED_APPS = [
    # 'daphne',
     'corsheaders',
    'channels',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    "whitenoise.runserver_nostatic",
    'rest_framework',
    'chatbot',
    # 'corsheaders',
    'psutil',
    'ai_config',

    'django_otp',  # Core OTP support
    'django_otp.plugins.otp_totp',  # Time-based OTP (TOTP)
    'django_otp.plugins.otp_static',  # Static OTP (backup codes)
    'two_factor',  # Two-factor authentication app
]
CORS_ALLOWED_ORIGINS = [
    "https://experimental.rahmn.tech",
    "http://localhost:8000",
    "http://127.0.0.1:8000",
]

CSRF_TRUSTED_ORIGINS = [
    "https://experimental.rahmn.tech",
    "http://localhost:8000",
    "http://127.0.0.1:8000",
]
# SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
     "whitenoise.middleware.WhiteNoiseMiddleware",
     'django_otp.middleware.OTPMiddleware',
     'chatbot.middleware.EnforceActiveSessionMiddleware',
     'corsheaders.middleware.CorsMiddleware',
    #  'corsheaders.middleware.CorsMiddleware', 
]

ROOT_URLCONF = 'ai_config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
          'DIRS': [BASE_DIR, "templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'ai_config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': config('DB_NAME', default='neurosys'),
        'USER': config('DB_USER', default=''),
        'PASSWORD': config('DB_PASSWORD', default=''),
        'HOST': config('DB_HOST', default='localhost'),
        'PORT': config('DB_PORT', default='5432'),
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = config('TIME_ZONE', default='Asia/Jakarta')

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
LOGIN_URL = '/login/'

ASGI_APPLICATION = "ai_config.asgi.application"
# ASGI_APPLICATION = "ai_config.asgi.application"
# CHANNEL_LAYERS = {
#     "default": {
#         "BACKEND": "channels.layers.InMemoryChannelLayer",
#     },
# }

CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [("127.0.0.1", 6379)],
        },
    },
}

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static")  # Hanya mengarah ke folder static yang benar
]   
STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")  # Tempat hasil collectstatic

CACHES = {
    'default': {
        'BACKEND': 'django_redis.cache.RedisCache',
        'LOCATION': 'redis://127.0.0.1:6379/1',  # Ganti dengan lokasi Redis Anda
        'OPTIONS': {
            'CLIENT_CLASS': 'django_redis.client.DefaultClient',
        }
    }
}
# Structured security records contain identifiers and verdicts, never raw tool data.
# Collect stderr with the service manager / external log collector.
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {"security_json": {"format": "%(message)s"}},
    "handlers": {"security_console": {"class": "logging.StreamHandler", "formatter": "security_json"}},
    "loggers": {"neurosys.security": {"handlers": ["security_console"], "level": "INFO", "propagate": False}},
}
SURICATA_AUTO_BLOCK_ENABLED = False
SURICATA_EVE_PATH = "/var/log/suricata/eve.json"
# Known-benign noisy signatures never stored as dashboard alerts
# (comma-separated; matched against the alert message, case-insensitive).
# Example: Suricata stream-event 2210044 fires per packet on ordinary
# dev-machine traffic and drowns real alerts.
SURICATA_SUPPRESS_SIGNATURES = [
    s.strip() for s in os.environ.get(
        "SURICATA_SUPPRESS_SIGNATURES",
        "SURICATA STREAM Packet with invalid timestamp",
    ).split(",") if s.strip()
]
# Identical alerts (same signature + endpoints) are stored at most once per
# window so one chatty flow cannot flood the dashboard. Seconds.
SURICATA_DEDUP_SECONDS = max(60, int(os.environ.get("SURICATA_DEDUP_SECONDS", "600")))
AGENT_APPROVAL_TIMEOUT_SECONDS = max(1, int(os.environ.get("AGENT_APPROVAL_TIMEOUT_SECONDS", "30")))
# Full Access mode: approval-required (non-blocked) actions are auto-approved
# and audited instead of waiting for a human click. Hard blocks (destructive
# commands, credential/identity paths) ALWAYS stay enforced and cannot be
# disabled by this switch. Flip to False to restore strict per-action scope.
AGENT_FULL_ACCESS_AUTO_APPROVE = config("AGENT_FULL_ACCESS_AUTO_APPROVE", default=True, cast=bool)
